### ISSUE TITLE
AES flag is missing 

### ISSUE THREAD

**Issue by gajrajkuldeep** [compressedsensing/comcrypt#13]
define flag AES_128_CONF in the file 'project-conf.h'.

**Comment by kasperlauge** [comment]
Can you explain a bit more? As I understand this is only if we want to change the original AES driver defined in https://github.com/contiki-ng/contiki-ng/blob/develop/os/lib/aes-128.h but we are using those functions.

**Comment by gajrajkuldeep** [comment]
As this flag is defined in the file D:\contiki-ng-develop\arch\platform\sky\contiki-conf.h by default it uses cc2420_aes_128_driver. Which selects Hardware version of AES for sky motes by defaults.  You need to change it so that the software version of AES is used.

**Comment by gajrajkuldeep** [comment]
These post might be helpful:
https://stackoverflow.com/questions/37382634/how-to-enable-message-encryption-in-contiki-cooja-simulator 
https://sourceforge.net/p/contiki/mailman/message/34200909/

**Comment by kasperlauge** [comment]
Oh thank you, nice catch! :) Apparently we have used the hardware version of the AES block encryption. We will look into what we do with that :)

**Comment by gajrajkuldeep** [comment]
I have created a simple program for selecting AES driver from hardware and software. The code for that is here: https://github.com/gajrajkuldeep/AES_hardware_software
